name: Build & Deploy Spring Boot App

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - feature/fix-google-auth

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          # Set deployment variables
          APP_NAME="hackathon-backend"
          APP_DIR="/opt/$APP_NAME"
          REPO_URL="https://github.com/hackathon-fii-practic-sahurbot3000/backend.git"
          BRANCH="main"
          
          echo "Starting deployment..."
          
          # Create app directory if it doesn't exist
          sudo mkdir -p $APP_DIR
          cd $APP_DIR
          
          # Clone or update repository
          if [ -d ".git" ]; then
            echo "Updating existing repository..."
            git fetch origin
            git reset --hard origin/$BRANCH
            git clean -fd
          else
            echo "Cloning repository..."
            sudo git clone $REPO_URL .
            git checkout $BRANCH
          fi
          
          # Make deploy script executable
          chmod +x scripts/deploy.sh
          
          # Run deployment script
          ./scripts/deploy.sh
          
          echo "Deployment completed!"
          
          # Show service status
          echo "=== Service Status ==="
          sudo systemctl is-active $APP_NAME || true
          
          # Show recent logs
          echo "=== Recent Logs ==="
          sudo journalctl -u $APP_NAME --no-pager --lines=20 || true
          
          # Test health endpoint
          echo "=== Health Check ==="
          sleep 10
          curl -f http://localhost:8080/actuator/health || echo "Health check failed"
